CREATE TABLE `FUND_INFO` (
`CODE` char(6) NOT NULL,
`NAME` varchar(255) NOT NULL,
`BUILD_DATE` char(8) NULL,
`INCOME_MONTH` double NULL,
`INCOME_THREE_MONTH` double NULL,
`INCOME_HALF_YEAR` double NULL,
`INCOME_YEAR` double NULL,
`UNIT_MONEY` double NULL,
`ASSET` double NULL,
PRIMARY KEY (`CODE`) 
);
CREATE TABLE `MANAGER_INFO` (
`CODE` char(8) NOT NULL,
`NAME` varchar(255) NOT NULL,
`WORK_YEAR` int NULL,
PRIMARY KEY (`CODE`) 
);
CREATE TABLE `FUND_MANAGER_RLN` (
`FUND_CODE` char(6) NOT NULL,
`MANAGER_CODE` char(8) NOT NULL,
PRIMARY KEY (`FUND_CODE`, `MANAGER_CODE`) 
);
CREATE TABLE `FUND_DATA_DAY` (
`FUND_CODE` char(6) NOT NULL,
`UPDATE_DATE` char(8) NOT NULL,
`STOCK_PERCENT` double NULL,
`CUSH_PERCENT` double NULL,
`OTHER_PERCENT` double NULL,
`UNIT_MONEY` double NOT NULL,
`EQUITY_RETURN` double NOT NULL,
PRIMARY KEY (`FUND_CODE`, `UPDATE_DATE`) 
);
CREATE TABLE `STOCK_INFO` (
`CODE` char(6) NOT NULL,
`NAME` varchar(255) NULL,
PRIMARY KEY (`CODE`) 
);
CREATE TABLE `FUND_STOCK_RLN` (
`FUND_CODE` char(6) NOT NULL,
`STOCK_CODE` char(6) NOT NULL,
`HOLD_PERCENT` double NULL,
`CHANGE_PERCENT` double NULL,
PRIMARY KEY (`FUND_CODE`, `STOCK_CODE`) 
);
CREATE TABLE `FUND_DATA_TIME` (
`FUND_CODE` char(6) NOT NULL,
`UPDATE_TIME` char(4) NOT NULL,
`UNIT_MONEY_EVALUATION` double NOT NULL,
`EQUITY_RETURN_EVALUATION` double NULL,
`UPDATE_DATE` char(8) NULL,
PRIMARY KEY (`FUND_CODE`, `UPDATE_TIME`) 
);
CREATE TABLE `FUND_STOCK_RLN_HIST` (
`FUND_CODE` char(6) NOT NULL,
`STOCK_CODE` char(6) NOT NULL,
`HOLD_PERCENT` double(255,0) NULL,
`UPDATE_DATE` char(8) NOT NULL,
PRIMARY KEY (`FUND_CODE`, `STOCK_CODE`, `UPDATE_DATE`) 
);

ALTER TABLE `FUND_MANAGER_RLN` ADD CONSTRAINT `MANGER_CODE_FK` FOREIGN KEY (`MANAGER_CODE`) REFERENCES `MANAGER_INFO` (`CODE`);
ALTER TABLE `FUND_MANAGER_RLN` ADD CONSTRAINT `FUND_CODE_FK` FOREIGN KEY (`FUND_CODE`) REFERENCES `FUND_INFO` (`CODE`);
ALTER TABLE `FUND_DATA_DAY` ADD CONSTRAINT `FUND_DATE_DAY_FUND_CODE` FOREIGN KEY (`FUND_CODE`) REFERENCES `FUND_INFO` (`CODE`);
ALTER TABLE `FUND_STOCK_RLN` ADD CONSTRAINT `FUND_STOCK_RLN_FUND_CODE` FOREIGN KEY (`FUND_CODE`) REFERENCES `FUND_INFO` (`CODE`);
ALTER TABLE `FUND_STOCK_RLN` ADD CONSTRAINT `FUND_STOCK_RLN_STOCK_CODE` FOREIGN KEY (`STOCK_CODE`) REFERENCES `STOCK_INFO` (`CODE`);
ALTER TABLE `FUND_DATA_TIME` ADD CONSTRAINT `FUND_DATA_TIME_FUND_CODE` FOREIGN KEY (`FUND_CODE`) REFERENCES `FUND_INFO` (`CODE`);
ALTER TABLE `FUND_STOCK_RLN_HIST` ADD CONSTRAINT `FUND_STOCK_RLN_HIST_FUND_CODE` FOREIGN KEY (`FUND_CODE`) REFERENCES `FUND_INFO` (`CODE`);
ALTER TABLE `FUND_STOCK_RLN_HIST` ADD CONSTRAINT `FUND_STOCK_RLN_HIST_STOCK_CODE` FOREIGN KEY (`STOCK_CODE`) REFERENCES `STOCK_INFO` (`CODE`);

